// Built-in example documents (same text as samples/generate.py) for trying the app without files.
export const SAMPLE_ORIGINAL = "<h1>Media Monitoring Services Agreement</h1><p>This Media Monitoring Services Agreement (the \"Agreement\") is entered into as of January 1, 2026 by and between Provider Inc. (\"Provider\") and Example Corp. (\"Customer\").</p><h2>1. Services</h2><p>Provider shall deliver daily media monitoring reports covering print, broadcast and online sources in the United States and Canada.</p><p>Reports will be delivered by email no later than 8:00 a.m. Eastern Time each business day.</p><h2>2. Fees and Payment</h2><p>Customer shall pay an annual subscription fee of $48,000, payable quarterly in advance. Invoices are due within thirty (30) days of receipt.</p><p>Late payments shall accrue interest at the rate of 1.5% per month.</p><h2>3. Term and Termination</h2><p>The initial term of this Agreement is twelve (12) months and shall automatically renew for successive one-year terms unless either party gives sixty (60) days written notice.</p><p>Either party may terminate this Agreement for material breach that remains uncured thirty (30) days after written notice.</p><h2>4. Confidentiality</h2><p>Each party shall protect the other party's Confidential Information using at least the same degree of care it uses to protect its own confidential information, but no less than reasonable care.</p><h2>5. Limitation of Liability</h2><p>In no event shall either party's aggregate liability exceed the fees paid by Customer in the twelve (12) months preceding the claim.</p><h2>6. Governing Law</h2><p>This Agreement shall be governed by the laws of the State of Illinois.</p>";

export const SAMPLE_REVISED = "<h1>Media Monitoring Services Agreement</h1><p>This Media Monitoring Services Agreement (the \"Agreement\") is entered into as of February 1, 2026 by and between Provider Inc. (\"Provider\") and Example Corp. (\"Customer\").</p><h2>1. Services</h2><p>Provider shall deliver daily media monitoring reports covering print, broadcast, podcast and online sources in the United States, Canada and Mexico.</p><p>Reports will be delivered through the online platform no later than 7:00 a.m. Eastern Time each business day.</p><p>Provider shall also deliver a monthly executive summary with share-of-voice analysis.</p><h2>2. Fees and Payment</h2><p>Customer shall pay an annual subscription fee of $52,500, payable annually in advance. Invoices are due within forty-five (45) days of receipt.</p><h2>3. Term and Termination</h2><p>The initial term of this Agreement is twenty-four (24) months and shall automatically renew for successive one-year terms unless either party gives ninety (90) days written notice.</p><p>Either party may terminate this Agreement for material breach that remains uncured thirty (30) days after written notice.</p><h2>4. Confidentiality</h2><p>Each party shall protect the other party's Confidential Information using at least the same degree of care it uses to protect its own confidential information, but no less than reasonable care.</p><h2>5. Limitation of Liability</h2><p>In no event shall either party's aggregate liability exceed the fees paid by Customer in the twelve (12) months preceding the claim.</p><h2>6. Governing Law</h2><p>This Agreement shall be governed by the laws of the State of Delaware.</p>";

export function sampleFiles(): [File, File] {
  return [
    new File([SAMPLE_ORIGINAL], 'sample-agreement-v1.html', { type: 'text/html' }),
    new File([SAMPLE_REVISED], 'sample-agreement-v2.html', { type: 'text/html' }),
  ];
}
